/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BFT_fork_Forker */

#ifndef _Included_BFT_fork_Forker
#define _Included_BFT_fork_Forker
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     BFT_fork_Forker
	 * Method:    sysfork
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_BFT_fork_Forker_sysfork
	  (JNIEnv *, jobject);

	/*
	 * Class:     BFT_fork_Forker
	 * Method:    sysexit
	 * Signature: ()I
	 */
	JNIEXPORT void JNICALL Java_BFT_fork_Forker_sysexit
	  (JNIEnv *, jobject);

/*
 * Class:     BFT_fork_Forker
 * Method:    sysexit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BFT_fork_Forker_syswait
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
